import type { Metadata } from "next";
import { cookies } from "next/headers";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DevNav from "@/components/dev-nav";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const themeCookie = cookieStore.get("vite-ui-theme")?.value;
	const initialTheme =
		themeCookie === "light" || themeCookie === "dark"
			? themeCookie
			: "dark";
	const themeScript = `(() => {
  try {
    const theme = ${JSON.stringify(initialTheme)};
    const key = "vite-ui-theme";
    localStorage.setItem(key, theme);
    const root = document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
    root.style.colorScheme = theme;
  } catch (_) {}
})();`;

	return (
		<html
			lang="en"
			className={initialTheme}
			style={{ colorScheme: initialTheme }}
		>
			<head>
				<Script id="theme-storage" strategy="beforeInteractive">
					{themeScript}
				</Script>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme={initialTheme}
					enableSystem={false}
					disableTransitionOnChange
				>
					<DevNav />
					<main>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
